version: "3.9"

services:
  app:
    build: .
    container_name: badminton_agent
    ports:
      - "8000:8000" # FastAPI
      - "8501:8501" # Streamlit
    env_file:
      - .env
    command: >
      sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
